name: BuildAndPublish
description: 'Build a .NET Framework project and publish the .nupkg to the feed'
inputs:
  SolutionName: 
    description: 'Name of the Solution'
    required: true
  BuildSolutionType:
    desciption: 'Build Configuration switch.'
    default: 'Release'
  User:
    description: 'UserName'
  Token:
    description: 'NugetToken'

runs:
  using: "composite"
  
  steps:     
      
  - uses: actions/checkout@v3
  
  - name: Setup MSBuild
    uses: microsoft/setup-msbuild@v1
    
  - name: Setup Nuget
    uses: NuGet/setup-nuget@v1.1.1
    
  - name: Navigate to Workspace
    run: cd $GITHUB_WORKSPACE
    shell: bash
    
  - name: Create Build Directory
    run: mkdir _build
    shell: bash
    
  - name: Add organization nuget feed
    run: dotnet nuget add source --username ${{ inputs.User }} --password ${{ inputs.Token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Aligned-Vision-Group-Engineering/index.json"
    shell: bash
    
    
  - name: Restore dependencies
    run: nuget restore
    shell: bash
    
  - name: Build Solution
    run: msbuild.exe ${{ inputs.SolutionName }}.sln
    shell: bash
    
    
    
  - name: Pack
    id: PackForNuget
    run: dotnet pack --configuration ${{ inputs.BuildSolutionType }}
    shell: bash

#  - name: Upload artifact
#    uses: actions/upload-artifact@v1.0.0
#    with:
#      name: inputs.SolutionName
#      path: '${{ inputs.SolutionName }}\bin\Release\'
    


  - name: Put To Nuget - from found nupkg
    run: dotnet nuget push **\*.nupkg --source github
    shell: bash
